---
abstract: A Cache Engine with Adaptive Lifetime Control by Load Average
author: 'Kazuho Oku <kazuhooku@gmail.com>'
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Cache-Adaptive-ByLoad
no_index:
  directory:
    - inc
    - t
requires:
  BSD::getloadavg: 0
  Cache::Adaptive: 0.03
  Class::Accessor::Fast: 0.3
  List::Util: 1.14
  Time::HiRes: 1.65
version: 0.01
